"""NTG - Multi-Provider LiteLLM Smart Router."""

from ntg.config import (
    COHERE_ACTUAL_MODEL,
    COHERE_KEYS,
    COHERE_LITELLM_MODEL,
    DEFAULT_GEMINI_KEYS,
    DEFAULT_KEYS,
    DEFAULT_LOGICAL_MODEL,
    GEMINI_API_KEY,
    GEMINI_KEYS,
    GROQ_KEYS,
    LITELLM_MODEL_NAME,
    MODEL_GROUP_COHERE,
    MODEL_GROUP_GEMINI,
    MODEL_GROUP_GROQ,
    MODEL_GROUP_NVIDIA,
    MODEL_GROUP_OPENROUTER,
    NVIDIA_ACTUAL_MODEL,
    NVIDIA_KEYS,
    NVIDIA_LITELLM_MODEL,
    OPENROUTER_ACTUAL_MODEL,
    OPENROUTER_FREE_MODEL,
    OPENROUTER_KEYS,
    OPENROUTER_LITELLM_MODEL,
)
from ntg.diagnostics import print_account_status, print_banner, print_request_execution
from ntg.discovery import (
    build_all_deployments,
    build_cohere_deployments,
    build_gemini_deployments,
    build_groq_deployments,
    build_nvidia_deployments,
    build_openrouter_deployments,
    discover_groq_models,
)
from ntg.exceptions import (
    classify_gemini_error,
    classify_openrouter_error,
    classify_provider_error,
    extract_error_payload,
)
from ntg.models import Account, Deployment, GeminiDeployment, utc_string
from ntg.router import OpenRouterFallbackRouter, UnifiedNTGRouter

__all__ = [
    "Deployment",
    "Account",
    "GeminiDeployment",
    "UnifiedNTGRouter",
    "OpenRouterFallbackRouter",
    "OPENROUTER_ACTUAL_MODEL",
    "OPENROUTER_FREE_MODEL",
    "OPENROUTER_LITELLM_MODEL",
    "NVIDIA_ACTUAL_MODEL",
    "NVIDIA_LITELLM_MODEL",
    "COHERE_ACTUAL_MODEL",
    "COHERE_LITELLM_MODEL",
    "LITELLM_MODEL_NAME",
    "DEFAULT_LOGICAL_MODEL",
    "MODEL_GROUP_OPENROUTER",
    "MODEL_GROUP_GROQ",
    "MODEL_GROUP_NVIDIA",
    "MODEL_GROUP_COHERE",
    "MODEL_GROUP_GEMINI",
    "OPENROUTER_KEYS",
    "GROQ_KEYS",
    "NVIDIA_KEYS",
    "COHERE_KEYS",
    "GEMINI_KEYS",
    "DEFAULT_KEYS",
    "DEFAULT_GEMINI_KEYS",
    "GEMINI_API_KEY",
    "build_all_deployments",
    "build_openrouter_deployments",
    "build_groq_deployments",
    "build_nvidia_deployments",
    "build_cohere_deployments",
    "build_gemini_deployments",
    "discover_groq_models",
    "extract_error_payload",
    "classify_openrouter_error",
    "classify_gemini_error",
    "classify_provider_error",
    "print_account_status",
    "print_banner",
    "print_request_execution",
    "utc_string",
]